name: CI-Validate Deployment

on:
    push:
      branches:
        - main
    schedule:
      - cron: '0 6,18 * * *'  # Runs at 6:00 AM and 6:00 PM GMT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version  # Verify installation

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          # Check if service principal exists
          az ad sp show --id ${{ secrets.AZURE_CLIENT_ID }}

      - name: Install Bicep CLI
        run: az bicep install

      - name: Generate Unique Solution Prefix and Environment Name
        id: generate_solution_prefix
        run: |
          set -e
          COMMON_PART="pslc"
          TIMESTAMP=$(date +%s)  
          UPDATED_TIMESTAMP=$(echo $TIMESTAMP | tail -c 3) 
          UNIQUE_SOLUTION_PREFIX="${COMMON_PART}${UPDATED_TIMESTAMP}"
          ENVIRONMENT_NAME="env-${UNIQUE_SOLUTION_PREFIX}"  # Dynamically generated environment name
          echo "SOLUTION_PREFIX=${UNIQUE_SOLUTION_PREFIX}" >> $GITHUB_ENV
          echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME}" >> $GITHUB_ENV
          echo "Generated SOLUTION_PREFIX: ${UNIQUE_SOLUTION_PREFIX}, ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}"

      - name: Deploy Bicep Template at Subscription Level
        id: deploy
        run: |
          set -e
          echo "Deploying bicep template at the subscription level...."
          deployment_output=$(az deployment sub create \
            --location WestUS \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            --template-file infra/main.bicep \
            --parameters \
                authClientId=${{ secrets.AZURE_CLIENT_ID }} \
                authClientSecret=${{ secrets.AZURE_CLIENT_SECRET }} \
                environmentName=${{ env.ENVIRONMENT_NAME }} \
                location=NorthCentralUS \
                principalId=${{ secrets.AZURE_PRINCIPAL_ID }} \
            --query "properties.outputs.webappName.value" --output json)

          # Extract the webapp name from JSON response using jq
          webapp_name=$(echo $deployment_output | jq -r .)
          echo "webapp_name=$webapp_name" >> $GITHUB_ENV
          echo "Deployment completed with webapp_name: $webapp_name"

      - name: Update Web App Docker Configuration
        run: |
          set -e
          echo "Updating the Web App to use the ACR Docker image..."
          
          # Use the dynamically retrieved web app name from the deployment step
          webapp_name=${{ env.webapp_name }}
          container_registry="byocgacontainerreg.azurecr.io"
          image_name="webapp:dev"
        
          # Set up Web App with the correct ACR image
          az webapp config container set \
            --name $webapp_name \
            --resource-group rg-${{ env.ENVIRONMENT_NAME }} \
            --docker-custom-image-name "$container_registry/$image_name" \
            --docker-registry-server-url "https://$container_registry" \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            --query "containerSettings" \
            --output json

      - name: List KeyVaults and Store in Array
        id: list_keyvaults
        run: |
          set -e
          echo "Listing all KeyVaults in the subscription..."
          
          # Get the list of KeyVaults in the subscription
          keyvaults=$(az resource list --resource-type "Microsoft.KeyVault/vaults" --query "[].name" -o tsv)

          if [ -z "$keyvaults" ]; then
            echo "No KeyVaults found in the subscription."
            echo "KEYVAULTS=[]" >> $GITHUB_ENV  # If no KeyVaults found, set an empty array
          else
            echo "KeyVaults found: $keyvaults"

            # Format the list into an array with proper formatting (no trailing comma)
            keyvault_array="[" 
            first=true
            for kv in $keyvaults; do
              if [ "$first" = true ]; then
                keyvault_array="$keyvault_array\"$kv\""
                first=false
              else
                keyvault_array="$keyvault_array,\"$kv\""
              fi
            done
            keyvault_array="$keyvault_array]"

            # Output the formatted array and save it to the environment variable
            echo "KEYVAULTS=$keyvault_array" >> $GITHUB_ENV
          fi
      
      - name: Delete Bicep Deployment
        if: success()
        run: |
          set -e
          echo "Deleting the resources from the subscription..."
          az deployment sub delete \
            --name rg-${{ env.ENVIRONMENT_NAME }} \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            --no-wait

      - name: Wait for resource deletion to complete
        run: |
          # List of KeyVaults and additional resources
          KEYVAULTS="${{ env.KEYVAULTS }}"

          # Remove the surrounding square brackets, if they exist
          stripped_keyvaults=$(echo "$KEYVAULTS" | sed 's/\[\|\]//g')
          
          # Convert the comma-separated string into an array
          IFS=',' read -r -a resources_to_check <<< "$stripped_keyvaults"
          
          # Append new resources to the array
          resources_to_check+=("${{ env.SOLUTION_PREFIX }}-openai" "${{ env.SOLUTION_PREFIX }}-cogser")

          echo "List of resources to check: ${resources_to_check[@]}"

          # Get the list of resources in YAML format
          resource_list=$(az resource list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --output yaml)

          # Maximum number of retries
          max_retries=3

          # Retry intervals in seconds (30, 60, 120)
          retry_intervals=(30 60 120)

          # Retry mechanism to check resources
          retries=0
          while true; do
            resource_found=false

            # Iterate through the resources to check
            for resource in "${resources_to_check[@]}"; do
              echo "Checking resource: $resource"
              if echo "$resource_list" | grep -q "name: $resource"; then
                echo "Resource '$resource' exists in the subscription."
                resource_found=true
              else
                echo "Resource '$resource' does not exist in the subscription."
              fi
            done

            # If any resource exists, retry
            if [ "$resource_found" = true ]; then
              retries=$((retries + 1))
              if [ "$retries" -ge "$max_retries" ]; then
                echo "Maximum retry attempts reached. Exiting."
                break
              else
                # Wait for the appropriate interval for the current retry
                echo "Waiting for ${retry_intervals[$retries-1]} seconds before retrying..."
                sleep ${retry_intervals[$retries-1]}
              fi
            else
              echo "No resources found. Exiting."
              break
            fi
          done

      - name: Purging the Resources
        if: success()
        run: |
          set -e 
          # Define variables
          OPENAI_COMMON_PART="-openai"
          openai_name="${{ env.SOLUTION_PREFIX }}${OPENAI_COMMON_PART}"
          echo "Azure OpenAI: $openai_name"

          MULTISERVICE_COMMON_PART="-cogser"
          multiservice_account_name="${{ env.SOLUTION_PREFIX }}${MULTISERVICE_COMMON_PART}"
          echo "Azure MultiService Account: $multiservice_account_name"

          # Purge OpenAI Resource
          echo "Purging the OpenAI Resource..."
          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$openai_name --verbose; then
            echo "Failed to purge openai resource: $openai_name"
          else
            echo "Purged the openai resource: $openai_name"
          fi
   
          # Purge MultiService Account Resource
          echo "Purging the MultiService Account Resource..."
          if ! az resource delete --ids /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/providers/Microsoft.CognitiveServices/locations/uksouth/deletedAccounts/$multiservice_account_name --verbose; then
            echo "Failed to purge multiService account resource: $multiservice_account_name"
          else
            echo "Purged the multiService account resource: $multiservice_account_name"
          fi

          # Ensure KEYVAULTS is properly formatted as a comma-separated string
          KEYVAULTS="${{ env.KEYVAULTS }}"

          # Remove the surrounding square brackets, if they exist
          stripped_keyvaults=$(echo "$KEYVAULTS" | sed 's/\[\|\]//g')
          
          # Convert the comma-separated string into an array
          IFS=',' read -r -a keyvault_array <<< "$stripped_keyvaults"

          echo "Using KeyVaults Array..."
          for keyvault_name in "${keyvault_array[@]}"; do
            echo "Processing KeyVault: $keyvault_name"
            # Check if the KeyVault is soft-deleted
            deleted_vaults=$(az keyvault list-deleted --query "[?name=='$keyvault_name']" -o json --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }})

            # If the KeyVault is found in the soft-deleted state, purge it
            if [ "$(echo "$deleted_vaults" | jq length)" -gt 0 ]; then
              echo "KeyVault '$keyvault_name' is soft-deleted. Proceeding to purge..."
              az keyvault purge --name "$keyvault_name" --no-wait
            else
              echo "KeyVault '$keyvault_name' is not soft-deleted. No action taken."
            fi
          done

          echo "Resource purging completed successfully"
      
      - name: Send Notification on Failure
        if: failure()
        run: |
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      
          # Construct the email body
          EMAIL_BODY=$(cat <<EOF
          {
            "body": "<p>Dear Team,</p><p>We would like to inform you that the Client Advisor Automation process has encountered an issue and has failed to complete successfully.</p><p><strong>Build URL:</strong> ${RUN_URL}<br> ${OUTPUT}</p><p>Please investigate the matter at your earliest convenience.</p><p>Best regards,<br>Your Automation Team</p>"
          }
          EOF
          )
      
          # Send the notification
          curl -X POST "${{ secrets.LOGIC_APP_URL }}" \
            -H "Content-Type: application/json" \
            -d "$EMAIL_BODY" || echo "Failed to send notification"
